# Generated by Django 4.2.11 on 2024-06-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('retired', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('speech_length', models.CharField(max_length=50)),
                ('mentions', models.TextField(blank=True, null=True)),
                ('thanks', models.TextField(blank=True, null=True)),
                ('additonal_preferences', models.TextField(blank=True, null=True)),
                ('dos_donts', models.TextField(blank=True, null=True)),
                ('attendees', models.CharField(blank=True, max_length=50, null=True)),
                ('tone_emotional', models.BooleanField(default=False)),
                ('tone_heartfelt', models.BooleanField(default=False)),
                ('tone_inspirational', models.BooleanField(default=False)),
                ('tone_happy', models.BooleanField(default=False)),
                ('tone_funny', models.BooleanField(default=False)),
                ('tone_formal', models.BooleanField(default=False)),
                ('tone_casual', models.BooleanField(default=False)),
                ('tone_motivational', models.BooleanField(default=False)),
                ('tone_reflective', models.BooleanField(default=False)),
                ('tone_others', models.CharField(blank=True, max_length=100, null=True)),
                ('user_input', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retirements',
            },
        ),
    ]
